### PR TITLE
Fix/reported author

### LINKED ISSUE #1297: The reported account's post does not have a Reported note on the Feed UI.
**Describe the bug**
When the user reports an account, the reported account's post does not have a Reported note and still visible on the Feed UI.

**To Reproduce**
1. Report an account.
2. Go to the Feed UI and look for the account's post.
3. Observe the reported account's post.

**Expected behavior**
The reported account's post should have a Reported note on the Feed UI.

**Attachment**
https://user-images.githubusercontent.com/79607355/134167087-f0e9ec6b-6ef5-4f6b-a406-9316007ee9d5.mp4

**Desktop/Laptop:**

    Toshiba Dynabook
    OS: Windows 10 pro
    Browser: Google Chrome
    Version 93.0.4577.82
    Browser: Firefox Version
    Version 92.0

**Smartphone:**

    Device: Sony Xperia 1
    OS: 11
    Browser Google Chrome
    Version 77.3865.103

    Device: Huawei P20
    OS: 10
    Browser Google Chrome
    Version 93.0.4577.82
    Browser MetaMask
    Version 3.3.0

    Device: iPhone XR
    OS: 15
    Browser Mozilla Firefox
    Version 19.1
    Browser MetaMask
    Version 3.3.0
    Browser Safari
    Version 15
    Browser Google Chrome
    Version 77.3865.103

**Wallet Used:**
Metamask

EP(ACP)

cc: @ggolcher

### PR DESCRIPTION
**Pull request by ghost**
## Checklist

- [ ] I have read the **README** document
- [ ] I have read the **CONTRIBUTING** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed
- [ ] My commit message follows [Conventional Commit Guideline](https://conventionalcommits.org/)

### CODE REVIEW

File: ui/plugins/bookmarks/src/components/entry-renderer.tsx [hunk 1]
```diff
@@ -95,13 +95,37 @@ const EntryCardRenderer = (props: IEntryCardRendererProps) => {
...
+        return t('reply');
+      case ItemTypes.TAG:
+        return t('tag');
+      default:
+        return t('unknown');
+    }
+  }, [t, type]);
+
+  const reportedTypeName = React.useMemo(() => {
+    if (accountAwaitingModeration) return `the author of this ${itemTypeName}`;
```
Comment (kenshyx) [inline ui/plugins/bookmarks/src/components/entry-renderer.tsx]: is is possible to have translated strings also here?

File: apps/akasha/src/components/post-page/post-page.tsx [hunk 2]
```diff
@@ -268,16 +268,16 @@ const PostPage: React.FC<IPostPageProps & RootComponentProps> = props => {
       <Helmet>
         <title>Post | Ethereum World</title>
       </Helmet>
-      {postReq.status === 'loading' && <EntryCardLoading />}
-      {postReq.status === 'error' && (
```
Comment (SeverS) [inline apps/akasha/src/components/post-page/post-page.tsx:273]: I don't understand these changes, are they part of a fix? postReq.status === 'loading' is the same as postReq.isLoading. isLoading is actually derived from the status state.
My point is that this is just a matter of preference and it does not affect the functionality in any way.

Comment (ghost) [reply apps/akasha/src/components/post-page/post-page.tsx:273]: True, not part of the fix, but I was under the impression we were slowly refactoring away from string literal checks to boolean flag checks when we see them.

**Comment by ghost** [comment]
@kenshyx If i got it right, the linked issue further explanation is indeed about hiding posts of reported authors in the feed. In that case I'll reopen the review.

File: ui/plugins/bookmarks/src/components/entry-renderer.tsx [hunk 3]
```diff
@@ -122,9 +122,9 @@ const EntryCardRenderer = (props: IEntryCardRendererProps) => {
   }, [t, type]);
 
   const reportedTypeName = React.useMemo(() => {
-    if (accountAwaitingModeration) return `the author of this ${itemTypeName}`;
-    return `this ${itemTypeName}`;
-  }, [accountAwaitingModeration, itemTypeName]);
+    if (accountAwaitingModeration) return t(`the author of this ${itemTypeName}`);
+    return t(`this ${itemTypeName}`);
```
Comment (kenshyx) [inline ui/plugins/bookmarks/src/components/entry-renderer.tsx]: I don't think that this can be extracted, apply the `t` only over the plain string without the `${itemTypeName}`

Comment (kenshyx) [reply ui/plugins/bookmarks/src/components/entry-renderer.tsx]: And concatenate them afterwards

**Review by kenshyx — APPROVED** [review]
