### PR TITLE
Fix: moderation app issues

### LINKED ISSUE #1301: [Android Mobile Web] The "Following" text and asset appear cut off inside its placeholder button on the Followers/Following UI when using a Huawei P20 device.
**Describe the bug**
When the user accesses the Followers/Following UI while using the Huawei P20 device on any browser (ex: Google Chrome), the "Following" text and asset are cut off inside its placeholder button.

**To Reproduce**
1. Open any mobile browser (ex: Google Chrome).
2. Go to the 'https://ethereum-world.netlify.app/social-app/feed' webpage and then log in to an account.
3. Access the Profile UI.
4. Tap the Followers or Following button.
5. On the Followers/Following UI, check the "Following" button.

**Expected behavior**
The "Following" text and asset appear should be displayed properly inside its placeholder button on the Followers/Following UI when using a Huawei P20 device.

**Attachments**
Following UI:
FollowingUI_The'Following'Text AssetAppearCutOffInsideItsPlaceholderButtonUsingHuaweiP20Device_SC

Followers UI:
FollowersUI_The'Following'Text AssetAppearCutOffInsideItsPlaceholderButtonUsingHuaweiP20Device_SC

**Device Used:**
- Huawei P20 | OS 10
-- Google Chrome Version 93.0.4577.82
-- MetaMask Browser Version 3.3.0 (777)
-- imToken Browser Version 2.9.6.1387

**Additional context**
- The issue was not able to check on the iOS mobile browser due to the unavailability of iOS as of the moment.
- The issue does not occur on the below devices and browsers:
- Realme C3 | OS 10
-- Google Chrome Version 93.0.4577.82
-- MetaMask Browser Version 3.3.0 (777)
- Samsung Galaxy Tab S6 Lite	| OS 11
-- MetaMask Browser Version 3.3.0 (777)
-- Chrome Version 93.0.4577.82
-- Google Chrome Version 93.0.4577.78

**Wallets Used:**
- Metamask Wallet
- imToken Wallet

EP (STFG)

cc: @ggolcher

### LINKED ISSUE #1324: User menu items are not displaying in the right order
**Describe the bug**
We should group the moderation items together and ensure there is correct capitalization

**To Reproduce**
Open the profile menu

**Expected behavior**
**Moderator dashboard** should be **Moderator Dashboard**
**Moderator Dashboard** should be AFTER **Send Us Feedback**

**Screenshots**
Screen Shot 2021-09-24 at 8 56 28 AM

**Desktop (please complete the following information):**
macOS 12.6, Chrome 94, MetaMask

### LINKED ISSUE #1330: [iOS Mobile Web] There are overlapping graphics and statistic data on the Stats tab of the Moderation History page when access to MetaMask browser.
**Describe the bug**
On the Stats tab of the Moderation History page, there are overlapping graphics and statistic data when access to MetaMask browser.

**To Reproduce**
1. Launch the MetaMask application then open its browser.
2. Go to the "https://ethereum-world.netlify.app/moderation-app/history" webpage.
3. Tap the Stats tab.
4. Observe the graphics and statistic data.

**Expected behavior**
The webpage should display the graphics and statistic data properly.

**Attachment**
Screenshot_OverlappingStatsDetails

**Device Used:**
 - iPad 10.2 inch (2020) (8th Gen)
 - OS: 15
 - Browsers and Versions:
 -- Google Chrome || Version 90.0.4430.216
 -- Firefox || Version 34.0 (4920)
 -- Safari || Version 15
 -- MetaMask Browser || Version 3.3.0

**Additional context**
The issue only occurs on:
- MetaMask Browser || Version 3.3.0

EP (CFG)

@ggolcher

### PR DESCRIPTION
**Pull request by josenriagu**
## Description

- fixes issues on moderation app and transparency log

## Checklist

- [x] I have read the **README** document
- [x] I have read the **CONTRIBUTING** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed
- [x] My commit message follows [Conventional Commit Guideline](https://conventionalcommits.org/)

### CODE REVIEW

File: apps/moderation/src/components/content-card/content-card.tsx [hunk 1]
```diff
@@ -44,26 +44,27 @@ const ContentCard: React.FC<Omit<IContentProps, 'entryData'>> = props => {
...
 
-  const profileDataReq = useGetProfile(entryId);
-  const profile = profileDataReq.data;
+  const profileDataQuery = useGetProfile(entryId, props.user, itemType === 'account');
+  const profile = profileDataQuery.data;
 
-  const postReq = usePost({ postId: entryId, enabler: !!entryId });
-  const commentReq = useComment(entryId);
+  const postQuery = usePost({ postId: entryId, enabler: itemType === 'post' });
+  const commentQuery = useComment(entryId, itemType === 'reply' || itemType === 'comment');
```
Comment (kenshyx) [inline apps/moderation/src/components/content-card/content-card.tsx]: aren't the item types declared somewhere already instead of manually specifying them?

File: apps/moderation/src/components/content-list.tsx [hunk 2]
```diff
@@ -250,28 +215,27 @@ const ContentList: React.FC<IContentListProps & RootComponentProps> = props => {
...
-        !isPending &&
-        (isDelisted && delistedItemPages.length ? (
+      {/* fetch indicator for load more on scroll */}
+      {pendingItemsQuery.isLoading && isPending && (
+        <Box pad="large">
+          <Spinner />
+        </Box>
+      )}
+      {!isPending &&
+        (!delistedItemsQuery.isLoading && isDelisted && delistedItemPages.length ? (
```
Comment (kenshyx) [inline apps/moderation/src/components/content-list.tsx]: it is better to reassign these expressions to a more verbose var(for readability) and could also be wrapped with `useMemo`

File: apps/moderation/src/components/content-card/content-card.tsx (hunk 1 above)
Comment (josenriagu) [reply apps/moderation/src/components/content-card/content-card.tsx]: defined now...

**Review by kenshyx — APPROVED** [review]
