### PR TITLE
fix/fixes 04

### LINKED ISSUE #1378: Moderation History profile image is not clickable. Also, moderator image does not show the name on hover in the list.
**Describe the bug**
Clicking on the profile image in Moderation History does not take a user to the moderator's profile. Also, hovering over a moderator's image in the left-hand list does not show a tooltip with their name

**To Reproduce**
Click on a moderator entry in the right, and hover on the left

**Expected behavior**
I expect to go to the moderator's page in the right, and for the tooltip to appear on hover in the left

**Device**
macOS 12.6, Chrome 94, MetaMask

**Screenshots**
Screen Shot 2021-10-11 at 1 21 17 PM

### LINKED ISSUE #1387: [Desktop Web] The notifications are not displayed on the Notification UI.
**Describe the bug**
When a user triggers a notification for another user, a red dot is displayed on the Notifications button but there are no notifications displayed. 

**To Reproduce**
1. Go to the "https://ethereum-world.netlify.app/social-app/feed" page.
2. Using another device with a different account, trigger a notification for another user(Repost the user's post).
3. Check the Notification on the other user.

**Expected behavior**
There should be a notification displayed on the Notification UI.

**Video**

https://user-images.githubusercontent.com/79607355/136972535-99c32c40-e744-4aa0-b3fc-9e5236588b05.mp4

**Desktop:**
 HP ProBook 4540s | Windows 10 Pro
- Google Chrome Version 94.0.4606.81

**Wallet Used:**
- MetaMask Web Extension

**Additional context**
- The notifications appear on mobile device.
- Notifications of any type do not appear on the Notification UI.

-GKM

CC: @ggolcher

### LINKED ISSUE #1394: Signed-off menu missing entry
**Describe the bug**
The feedback entry is not present for the mobile signed-off menu

**To Reproduce**
Tap the 3 dots when signed off

**Expected behavior**
We should have the feedback entry there

**Screenshots**
Screen Shot 2021-10-13 at 1 37 49 PM

**Platform**
Chrome, MetaMask

### LINKED ISSUE #1395: Tooltips have no margins on mobile
**Describe the bug**
Tooltips have no margins and look messy

**To Reproduce**
Get a tooltip (edit time, copy address, etc.)

**Expected behavior**
There should be the margins specified in the tooltip design

**Screenshots**
Screen Shot 2021-10-13 at 1 26 13 PM

**Platform**
Chrome, MetaMask

### LINKED ISSUE #1396: Background color is wrong for contextual actions
**Describe the bug**
Contextual actions have either a light-gray opaque background, or a light-gray translucent background.

**To Reproduce**
Tap the 3 dots in a post or in a profile

**Expected behavior**
The background color should be the same translucency and color as the slider or sign up overlays

**Screenshots**
Screen Shot 2021-10-13 at 1 32 18 PM
Screen Shot 2021-10-13 at 1 36 22 PM
Screen Shot 2021-10-13 at 1 26 31 PM

**Platform**
Chrome, MetaMask

### LINKED ISSUE #1401: Notifications appear as read, but unseen dot still appears
**Describe the bug**
After seeing all notifications, the unseen dot still shows

**To Reproduce**
Go to Notifications, see all unseen notifications. Check out the Notifications icon.

**Expected behavior**
The red dot should disappear from the icon.

**Screenshots**
Screen Shot 2021-10-13 at 1 53 46 PM

**Platform**
Chrome, MetaMask

### PR DESCRIPTION
**Pull request by ghost**
## Checklist

- [ ] I have read the **README** document
- [ ] I have read the **CONTRIBUTING** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed
- [ ] My commit message follows [Conventional Commit Guideline](https://conventionalcommits.org/)

### CODE REVIEW

File: apps/moderation/src/components/transparency-log.tsx [hunk 1]
```diff
@@ -172,7 +174,7 @@ const TransparencyLog: React.FC<ITransparencyLogProps> = props => {
             <DetailCard
               selected={selected}
               ipfsGateway={ipfsGateway}
-              handleClickAvatar={handleClickAvatar}
+              handleClickAvatar={handleClickAvatar(selected.moderator.pubKey)}
```
Comment (quininez) [inline apps/moderation/src/components/transparency-log.tsx]: guard for undefined moderator

File: apps/moderation/src/components/transparency-log.tsx [hunk 2]
```diff
@@ -184,7 +186,7 @@ const TransparencyLog: React.FC<ITransparencyLogProps> = props => {
               <DetailCard
                 selected={selected}
                 ipfsGateway={ipfsGateway}
-                handleClickAvatar={handleClickAvatar}
+                handleClickAvatar={handleClickAvatar(selected.moderator.pubKey)}
```
Comment (quininez) [inline apps/moderation/src/components/transparency-log.tsx]: also here

**Review by quininez — APPROVED** [review]
